remove libffi; add ghc-pkg; update kinit, kio, kde-gtk-config, libksysguard, mlt, spice-gtk, clang, llvm, libcxx, libcxxabi

diff --git a/gentoo.patch b/gentoo.patch
--- a/gentoo.patch
+++ b/gentoo.patch
@@ -78,33 +78,26 @@ index 8c97fdd3912..f4ca9bf78bc 100644
  	ECONF_SOURCE="${S}" econf $(use_enable static-libs static)
  }
  
-diff --git a/dev-libs/libffi/libffi-3.3-r2.ebuild b/dev-libs/libffi/libffi-3.3-r2.ebuild
-index 3d1f2530f8f..721d8c01f88 100644
---- a/dev-libs/libffi/libffi-3.3-r2.ebuild
-+++ b/dev-libs/libffi/libffi-3.3-r2.ebuild
-@@ -49,19 +49,8 @@ src_prepare() {
+diff --git a/eclass/ghc-package.eclass b/eclass/ghc-package.eclass
+index 8c77ad5bc3c..014c1d1e21e 100644
+--- a/eclass/ghc-package.eclass
++++ b/eclass/ghc-package.eclass
+@@ -58,11 +58,11 @@ ghc-getghcpkg() {
+ # because for some reason the global package file
+ # must be specified
+ ghc-getghcpkgbin() {
+-	local empty_db="${T}/empty.conf.d" ghc_pkg="$(ghc-libdir)/bin/ghc-pkg"
++	local empty_db="${T}/empty.conf.d" ghc_pkg="$(ghc-libdir)/../bin/ghc-pkg"
+ 	if [[ ! -d ${empty_db} ]]; then
+ 		"${ghc_pkg}" init "${empty_db}" || die "Failed to initialize empty global db"
+ 	fi
+-	echo "$(ghc-libdir)/bin/ghc-pkg" "--global-package-db=${empty_db}"
++	echo "$(ghc-libdir)/../bin/ghc-pkg" "--global-package-db=${empty_db}"
  }
  
- multilib_src_configure() {
--	# --includedir= path maintains a few properties:
--	# 1. have stable name across libffi versions: some packages like
--	#    dev-lang/ghc or kde-frameworks/networkmanager-qt embed
--	#    ${includedir} at build-time. Don't require those to be
--	#    rebuilt unless SONAME changes. bug #695788
--	#
--	#    We use /usr/.../${PN} (instead of former /usr/.../${P}).
--	#
--	# 2. have ${ABI}-specific location as ffi.h is target-dependent.
--	#
--	#    We use /usr/$(get_libdir)/... to have ABI identifier.
-+	use userland_BSD && export HOST="${CHOST}"
- 	econf \
--		--includedir="${EPREFIX}"/usr/$(get_libdir)/${PN}/include \
- 		--disable-multi-os-directory \
- 		$(use_enable static-libs static) \
- 		$(use_enable pax-kernel pax_emutramp) \
+ # @FUNCTION: ghc-version
 diff --git a/eclass/linux-mod.eclass b/eclass/linux-mod.eclass
-index 6a820371b76..7bcc63d864a 100644
+index b7c13cbf7e7..59896741679 100644
 --- a/eclass/linux-mod.eclass
 +++ b/eclass/linux-mod.eclass
 @@ -664,6 +664,7 @@ linux-mod_src_compile() {
@@ -198,10 +191,10 @@ index cd237a5abc5..725b73f6a71 100644
  	)
  
  	ecm_src_configure
-diff --git a/kde-frameworks/kinit/kinit-5.94.0.ebuild b/kde-frameworks/kinit/kinit-5.94.0.ebuild
+diff --git a/kde-frameworks/kinit/kinit-5.95.0.ebuild b/kde-frameworks/kinit/kinit-5.95.0.ebuild
 index c5b8ff4ba1b..2d0407fb117 100644
---- a/kde-frameworks/kinit/kinit-5.94.0.ebuild
-+++ b/kde-frameworks/kinit/kinit-5.94.0.ebuild
+--- a/kde-frameworks/kinit/kinit-5.95.0.ebuild
++++ b/kde-frameworks/kinit/kinit-5.95.0.ebuild
 @@ -43,8 +43,8 @@ src_configure() {
  	local mycmakeargs=(
  		$(cmake_use_find_package caps Libcap)
@@ -212,10 +205,10 @@ index c5b8ff4ba1b..2d0407fb117 100644
  	)
  
  	ecm_src_configure
-diff --git a/kde-frameworks/kio/kio-5.94.0.ebuild b/kde-frameworks/kio/kio-5.94.0.ebuild
+diff --git a/kde-frameworks/kio/kio-5.95.0.ebuild b/kde-frameworks/kio/kio-5.95.0.ebuild
 index d279d7e8c4b..94a24486aff 100644
---- a/kde-frameworks/kio/kio-5.94.0.ebuild
-+++ b/kde-frameworks/kio/kio-5.94.0.ebuild
+--- a/kde-frameworks/kio/kio-5.95.0.ebuild
++++ b/kde-frameworks/kio/kio-5.95.0.ebuild
 @@ -77,7 +77,7 @@ src_configure() {
  		$(cmake_use_find_package handbook KF5DocTools)
  		$(cmake_use_find_package kerberos GSSAPI)
@@ -225,11 +218,11 @@ index d279d7e8c4b..94a24486aff 100644
  	)
  
  	ecm_src_configure
-diff --git a/kde-plasma/kde-gtk-config/kde-gtk-config-5.24.5.ebuild b/kde-plasma/kde-gtk-config/kde-gtk-config-5.24.5.ebuild
-index 8bbe52c868c..2fe004cdfcf 100644
---- a/kde-plasma/kde-gtk-config/kde-gtk-config-5.24.5.ebuild
-+++ b/kde-plasma/kde-gtk-config/kde-gtk-config-5.24.5.ebuild
-@@ -18,7 +18,6 @@ KEYWORDS="amd64 ~arm arm64 ~ppc64 ~riscv x86"
+diff --git a/kde-plasma/kde-gtk-config/kde-gtk-config-5.25.1.ebuild b/kde-plasma/kde-gtk-config/kde-gtk-config-5.25.1.ebuild
+index 4aac79cd582..d86d0a9ba7b 100644
+--- a/kde-plasma/kde-gtk-config/kde-gtk-config-5.25.1.ebuild
++++ b/kde-plasma/kde-gtk-config/kde-gtk-config-5.25.1.ebuild
+@@ -18,7 +18,6 @@ KEYWORDS="~amd64 ~arm ~arm64 ~ppc64 ~riscv ~x86"
  IUSE=""
  
  DEPEND="
@@ -237,11 +230,11 @@ index 8bbe52c868c..2fe004cdfcf 100644
  	dev-libs/glib:2
  	>=dev-qt/qtdbus-${QTMIN}:5
  	>=dev-qt/qtgui-${QTMIN}:5
-diff --git a/kde-plasma/libksysguard/libksysguard-5.24.5-r1.ebuild b/kde-plasma/libksysguard/libksysguard-5.24.5-r1.ebuild
-index 664a0d85612..d1d3e7566d5 100644
---- a/kde-plasma/libksysguard/libksysguard-5.24.5-r1.ebuild
-+++ b/kde-plasma/libksysguard/libksysguard-5.24.5-r1.ebuild
-@@ -69,7 +69,7 @@ src_configure() {
+diff --git a/kde-plasma/libksysguard/libksysguard-5.25.1.ebuild b/kde-plasma/libksysguard/libksysguard-5.25.1.ebuild
+index 793ba7aba4c..5404b3eed68 100644
+--- a/kde-plasma/libksysguard/libksysguard-5.25.1.ebuild
++++ b/kde-plasma/libksysguard/libksysguard-5.25.1.ebuild
+@@ -64,7 +64,7 @@ src_configure() {
  	local mycmakeargs=(
  		$(cmake_use_find_package webengine Qt5WebChannel)
  		$(cmake_use_find_package webengine Qt5WebEngineWidgets)
@@ -250,10 +243,10 @@ index 664a0d85612..d1d3e7566d5 100644
  	)
  
  	ecm_src_configure
-diff --git a/media-libs/mlt/mlt-7.6.0.ebuild b/media-libs/mlt/mlt-7.6.0.ebuild
-index d55bd87549e..1a56960be16 100644
---- a/media-libs/mlt/mlt-7.6.0.ebuild
-+++ b/media-libs/mlt/mlt-7.6.0.ebuild
+diff --git a/media-libs/mlt/mlt-7.8.0.ebuild b/media-libs/mlt/mlt-7.8.0.ebuild
+index 0415d23c449..042f56b853e 100644
+--- a/media-libs/mlt/mlt-7.8.0.ebuild
++++ b/media-libs/mlt/mlt-7.8.0.ebuild
 @@ -59,7 +59,7 @@ DEPEND="
  	)
  	rubberband? ( media-libs/rubberband )
@@ -293,11 +286,11 @@ index cd70327db01..d2d56536d98 100644
  		--disable-qt6
  		--enable-qt5
  		--with-qmake=$(qt5_get_bindir)/qmake
-diff --git a/net-misc/spice-gtk/spice-gtk-0.39-r2.ebuild b/net-misc/spice-gtk/spice-gtk-0.39-r2.ebuild
-index e4af25b8d05..7439d916952 100644
---- a/net-misc/spice-gtk/spice-gtk-0.39-r2.ebuild
-+++ b/net-misc/spice-gtk/spice-gtk-0.39-r2.ebuild
-@@ -94,6 +94,7 @@ src_prepare() {
+diff --git a/net-misc/spice-gtk/spice-gtk-0.40.ebuild b/net-misc/spice-gtk/spice-gtk-0.40.ebuild
+index 357e2deefa6..3d361a40621 100644
+--- a/net-misc/spice-gtk/spice-gtk-0.40.ebuild
++++ b/net-misc/spice-gtk/spice-gtk-0.40.ebuild
+@@ -99,6 +99,7 @@ src_prepare() {
  
  src_configure() {
  	local emesonargs=(
@@ -317,10 +310,10 @@ index 0d212005d51..343d88c82bb 100644
  	append-lfs-flags #760857
  	multilib-minimal_src_configure
  }
-diff --git a/sys-devel/clang/clang-14.0.4.ebuild b/sys-devel/clang/clang-14.0.4.ebuild
-index 9039d230288..e1da1d82225 100644
---- a/sys-devel/clang/clang-14.0.4.ebuild
-+++ b/sys-devel/clang/clang-14.0.4.ebuild
+diff --git a/sys-devel/clang/clang-14.0.5.ebuild b/sys-devel/clang/clang-14.0.5.ebuild
+index ed84f3755fa..a2a46062a93 100644
+--- a/sys-devel/clang/clang-14.0.5.ebuild
++++ b/sys-devel/clang/clang-14.0.5.ebuild
 @@ -23,8 +23,11 @@ IUSE="
  REQUIRED_USE="${PYTHON_REQUIRED_USE}"
  RESTRICT="!test? ( test )"
@@ -398,7 +391,7 @@ index 9039d230288..e1da1d82225 100644
  	# - clang-X
  	# - clang -> clang-X
 diff --git a/sys-devel/distcc/distcc-3.4-r1.ebuild b/sys-devel/distcc/distcc-3.4-r1.ebuild
-index 7495c3fff4f..0c5270b545e 100644
+index 1bee4f2f642..dfee68afeec 100644
 --- a/sys-devel/distcc/distcc-3.4-r1.ebuild
 +++ b/sys-devel/distcc/distcc-3.4-r1.ebuild
 @@ -73,6 +73,7 @@ src_configure() {
@@ -422,11 +415,11 @@ index 9bd470297df..fd481026e27 100644
  
  [Install]
  WantedBy=multi-user.target
-diff --git a/sys-devel/llvm/llvm-14.0.4.ebuild b/sys-devel/llvm/llvm-14.0.4.ebuild
-index ee76f3f1b00..aba0c2222fa 100644
---- a/sys-devel/llvm/llvm-14.0.4.ebuild
-+++ b/sys-devel/llvm/llvm-14.0.4.ebuild
-@@ -22,6 +22,8 @@ KEYWORDS="amd64 ~arm arm64 ~ppc ppc64 ~riscv ~sparc x86 ~amd64-linux ~ppc-macos
+diff --git a/sys-devel/llvm/llvm-14.0.5.ebuild b/sys-devel/llvm/llvm-14.0.5.ebuild
+index ad91093de64..8c35fa2c992 100644
+--- a/sys-devel/llvm/llvm-14.0.5.ebuild
++++ b/sys-devel/llvm/llvm-14.0.5.ebuild
+@@ -22,6 +22,8 @@ KEYWORDS="~amd64 ~arm ~arm64 ~ppc ~ppc64 ~riscv ~sparc ~x86 ~amd64-linux ~ppc-ma
  IUSE="+binutils-plugin debug doc exegesis libedit +libffi ncurses test xar xml z3"
  RESTRICT="!test? ( test )"
  
@@ -475,10 +468,10 @@ index ee76f3f1b00..aba0c2222fa 100644
  
  		-DLLVM_HOST_TRIPLE="${CHOST}"
  
-diff --git a/sys-libs/libcxx/libcxx-14.0.4.ebuild b/sys-libs/libcxx/libcxx-14.0.4.ebuild
-index b9c4cd77b5b..039f2231044 100644
---- a/sys-libs/libcxx/libcxx-14.0.4.ebuild
-+++ b/sys-libs/libcxx/libcxx-14.0.4.ebuild
+diff --git a/sys-libs/libcxx/libcxx-14.0.5.ebuild b/sys-libs/libcxx/libcxx-14.0.5.ebuild
+index 4d6be5bcc7f..45373883e66 100644
+--- a/sys-libs/libcxx/libcxx-14.0.5.ebuild
++++ b/sys-libs/libcxx/libcxx-14.0.5.ebuild
 @@ -133,6 +133,7 @@ multilib_src_configure() {
  		-DLLVM_ENABLE_RUNTIMES=libcxx
  		-DLLVM_INCLUDE_TESTS=OFF
@@ -487,10 +480,10 @@ index b9c4cd77b5b..039f2231044 100644
  
  		-DLIBCXX_ENABLE_SHARED=ON
  		-DLIBCXX_ENABLE_STATIC=$(usex static-libs)
-diff --git a/sys-libs/libcxxabi/libcxxabi-14.0.4.ebuild b/sys-libs/libcxxabi/libcxxabi-14.0.4.ebuild
-index d8cef90dd97..4f8fb84c8fe 100644
---- a/sys-libs/libcxxabi/libcxxabi-14.0.4.ebuild
-+++ b/sys-libs/libcxxabi/libcxxabi-14.0.4.ebuild
+diff --git a/sys-libs/libcxxabi/libcxxabi-14.0.5.ebuild b/sys-libs/libcxxabi/libcxxabi-14.0.5.ebuild
+index 7d864cba362..530c2e82825 100644
+--- a/sys-libs/libcxxabi/libcxxabi-14.0.5.ebuild
++++ b/sys-libs/libcxxabi/libcxxabi-14.0.5.ebuild
 @@ -79,6 +79,7 @@ multilib_src_configure() {
  		-DLIBCXXABI_INCLUDE_TESTS=$(usex test)
  		-DLIBCXXABI_USE_LLVM_UNWINDER=$(usex libunwind)
