gentoo.patch: dev-lang/rust: add 1.42.0, update mesa to 20.0.2

diff --git a/gentoo.patch b/gentoo.patch
--- a/gentoo.patch
+++ b/gentoo.patch
@@ -103,6 +103,92 @@ index 6b165c5733..134827b507 100644
  		$(use_with xen xen_opt)
  		--without-ikvm-native
  		--disable-dtrace
+diff --git a/dev-lang/rust/rust-1.42.0.ebuild b/dev-lang/rust/rust-1.42.0.ebuild
+index 89ac74e333..bd8e89aa15 100644
+--- a/dev-lang/rust/rust-1.42.0.ebuild
++++ b/dev-lang/rust/rust-1.42.0.ebuild
+@@ -3,7 +3,7 @@
+ 
+ EAPI=7
+ 
+-PYTHON_COMPAT=( python3_{6,7} )
++PYTHON_COMPAT=( python3_{6,7,8} )
+ 
+ inherit bash-completion-r1 check-reqs estack flag-o-matic llvm multiprocessing multilib-build python-any-r1 rust-toolchain toolchain-funcs
+ 
+@@ -50,12 +50,13 @@ IUSE="clippy cpu_flags_x86_sse2 debug doc libressl miri nightly parallel-compile
+ # 3. Specify LLVM_MAX_SLOT, e.g. 9.
+ LLVM_DEPEND="
+ 	|| (
++		sys-devel/llvm:10[${LLVM_TARGET_USEDEPS// /,}]
+ 		sys-devel/llvm:9[${LLVM_TARGET_USEDEPS// /,}]
+ 		wasm? ( =sys-devel/lld-9* )
+ 	)
+-	<sys-devel/llvm-10:=
++	<sys-devel/llvm-11:=
+ "
+-LLVM_MAX_SLOT=9
++LLVM_MAX_SLOT=10
+ 
+ BOOTSTRAP_DEPEND="|| ( >=dev-lang/rust-1.$(($(ver_cut 2) - 1)).0-r1 >=dev-lang/rust-bin-1.$(($(ver_cut 2) - 1)) )"
+ 
+@@ -66,7 +67,6 @@ COMMON_DEPEND="
+ 	sys-libs/zlib:=
+ 	!libressl? ( dev-libs/openssl:0= )
+ 	libressl? ( dev-libs/libressl:0= )
+-	elibc_musl? ( sys-libs/libunwind )
+ 	system-llvm? (
+ 		${LLVM_DEPEND}
+ 	)
+@@ -125,6 +125,10 @@ pre_build_checks() {
+ 	check-reqs_pkg_setup
+ }
+ 
++clear_vendor_checksums() {
++	sed -i 's/\("files":{\)[^}]*/\1/' vendor/$1/.cargo-checksum.json
++}
++
+ pkg_pretend() {
+ 	pre_build_checks
+ }
+@@ -158,6 +162,9 @@ src_prepare() {
+ 			--destdir="${rust_stage0_root}" --prefix=/ || die
+ 	fi
+ 
++	clear_vendor_checksums libc
++	clear_vendor_checksums libgit2-sys
++
+ 	default
+ }
+ 
+@@ -348,6 +355,11 @@ src_install() {
+ 
+ 	insinto /etc/env.d/rust
+ 	doins "${T}/provider-${P}"
++
++	# remove some clutter
++	pushd "${ED}/usr/lib/rustlib"
++	rm components install.log manifest-* rust-installer-version uninstall.sh || die
++	popd
+ }
+ 
+ pkg_postinst() {
+@@ -367,15 +379,6 @@ pkg_postinst() {
+ 	if has_version app-editors/gvim || has_version app-editors/vim; then
+ 		elog "install app-vim/rust-vim to get vim support for rust."
+ 	fi
+-
+-	if use elibc_musl; then
+-		ewarn "${PN} on *-musl targets is configured with crt-static"
+-		ewarn ""
+-		ewarn "you will need to set RUSTFLAGS=\"-C target-feature=-crt-static\" in make.conf"
+-		ewarn "to use it with portage, otherwise you may see failures like"
+-		ewarn "error: cannot produce proc-macro for serde_derive v1.0.98 as the target "
+-		ewarn "x86_64-unknown-linux-musl does not support these crate types"
+-	fi
+ }
+ 
+ pkg_postrm() {
 diff --git a/dev-libs/glib/glib-2.62.5.ebuild b/dev-libs/glib/glib-2.62.5.ebuild
 index 33a36d9a29..11a0f1355f 100644
 --- a/dev-libs/glib/glib-2.62.5.ebuild
@@ -259,7 +345,7 @@ index 66266a5b54..0f912d776c 100644
  		powerpc64le*) echo powerpc64le-unknown-linux-gnu;;
  		powerpc64*)   echo powerpc64-unknown-linux-gnu;;
 diff --git a/kde-apps/kwave/kwave-19.12.3.ebuild b/kde-apps/kwave/kwave-19.12.3.ebuild
-index 90864a6bd2..6881491328 100644
+index ed2fc5023e..610527a3c6 100644
 --- a/kde-apps/kwave/kwave-19.12.3.ebuild
 +++ b/kde-apps/kwave/kwave-19.12.3.ebuild
 @@ -61,7 +61,6 @@ RDEPEND="
@@ -304,10 +390,10 @@ index 1a1ff9ab65..0df25aeb63 100644
  	"
  
  S="${WORKDIR}/${PN}-${MY_COMMIT}"
-diff --git a/media-libs/mesa/mesa-20.0.1-r1.ebuild b/media-libs/mesa/mesa-20.0.1-r1.ebuild
+diff --git a/media-libs/mesa/mesa-20.0.2.ebuild b/media-libs/mesa/mesa-20.0.2.ebuild
 index 8997f8d06a..d621673607 100644
---- a/media-libs/mesa/mesa-20.0.1-r1.ebuild
-+++ b/media-libs/mesa/mesa-20.0.1-r1.ebuild
+--- a/media-libs/mesa/mesa-20.0.2.ebuild
++++ b/media-libs/mesa/mesa-20.0.2.ebuild
 @@ -147,9 +147,10 @@ RDEPEND="${RDEPEND}
  # 1. List all the working slots (with min versions) in ||, newest first.
  # 2. Update the := to specify *max* version, e.g. < 10.
