remove multilib, never used anyway

diff --git a/sys-libs/musl/files/ldconfig.in b/sys-libs/musl/files/ldconfig.in
--- a/sys-libs/musl/files/ldconfig.in
+++ b/sys-libs/musl/files/ldconfig.in
@@ -38,7 +38,7 @@ get_options() {
 			;;
 		n|N|C|p)
 			echo "Unimplemented option: -$opt" >&2
-			exit 0
+			exit 1
 			;;
 		esac
 	done
@@ -125,9 +125,18 @@ get_options "$@"
 drs=$(read_ldso_conf "$LDSO_CONF")
 drs=$(sanitize $drs)
 
-ETC_LDSO_PATH=/etc/ld-musl.path
+ARCH=@@ARCH@@
+LDSO_PATH="/lib/ld-musl-${ARCH}.so.1"
+if [[ ! -e $LDSO_PATH ]]; then
+	echo "$LDSO_PATH not found" >&2
+	exit 1
+fi
 
-X=$(mktemp -p /tmp ld-musl.XXXXXX)
+LDSO_ARCH=$(basename $LDSO_PATH)
+LDSO_NAME=${LDSO_ARCH%.so.1}
+ETC_LDSO_PATH=/etc/${LDSO_NAME}.path
+
+X=$(mktemp -p /tmp ${LDSO_NAME}.XXXXXX)
 for d in $drs; do
 	echo $d >> $X
 done
