dev-dotnet/dotnet-runtime: pick correct compiler

diff --git a/dev-dotnet/dotnet-runtime/files/sane-buildflags.patch b/dev-dotnet/dotnet-runtime/files/sane-buildflags.patch
--- a/dev-dotnet/dotnet-runtime/files/sane-buildflags.patch
+++ b/dev-dotnet/dotnet-runtime/files/sane-buildflags.patch
@@ -47,3 +47,16 @@
 -    add_compile_options($<$<CONFIG:Release>:-O3>)
      add_compile_options($<$<CONFIG:RelWithDebInfo>:-O2>)
  endif()
+--- a/eng/native/init-compiler.sh	2021-10-22 18:18:54.119775546 +0200
++++ b/eng/native/init-compiler.sh	2021-10-22 18:19:04.391901380 +0200
+@@ -94,10 +94,6 @@
+         if [[ -z "$CXX" ]]; then CXX="$(command -v "$cxxCompiler")"; fi
+     fi
+ else
+-    if [[ ! -f "$CLR_CC" ]]; then
+-        echo "ERROR: CLR_CC is set but path '$CLR_CC' does not exist"
+-        exit 1
+-    fi
+     CC="$CLR_CC"
+     CXX="$CLR_CXX"
+ fi
